### ISSUE TITLE
Consider adding normalization rule for azides

### ISSUE THREAD

**Issue by greglandrum** [chembl/ChEMBL_Structure_Pipeline#18]
I was surprised to see this form of an azide in the database:
![image](https://user-images.githubusercontent.com/540511/90903575-6970f500-e3ce-11ea-9c25-c74e5f28ee76.png)
It's an odd form and I only find it once in ChEMBL26 (https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL1652082/)
in contrast to the >3200 structures which have `C-N=[N+]=[N-]` but I guess it's worth fixing just in case it shows up in future loads?

**Comment by eloyfelix** [comment]
done in #46
