### ISSUE TITLE
Package on conda-forge

### ISSUE THREAD

**Issue by hadim** [chembl/ChEMBL_Structure_Pipeline#19]
Would that be possible to transfer the conda package to conda-forge?

**Comment by eloyfelix** [comment]
Hi Hadrien, first of all thanks for transfering FPSim2 to conda-forge!

I've never done that but we would also be happy to have our structure pipeline in conda-forge. I'm on holidays for a couple of weeks but I'm happy to take a look at it when I'm back. Would appriciate any kind of guidance.

**Comment by hadim** [comment]
I am taking care of it at https://github.com/conda-forge/staged-recipes/pull/12535

**Comment by hadim** [comment]
PR has been merged. `conda install chembl_structure_pipeline` should work in less than an hour.

**Comment by eloyfelix** [comment]
awesome, many thanks!
