### ISSUE TITLE
conflict during installation

### ISSUE THREAD

**Issue by nbosc** [chembl/ChEMBL_Structure_Pipeline#21]
Despite having a running conda environment with chembl_structure_pipeline installed, every new environnement I create fail to install the package. Issue is:

```
(early_2021) C02XJ285JGH6:~ nbosc$ conda install -c chembl chembl_structure_pipeline
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

**Comment by greglandrum** [comment]
Hi @nbosc ,
Which python version/OS are you using? Do you have conda-forge in your list of channels?

I was able to install the package in a new conda environment without problems. Just to be sure, could you please try starting from an environment where only python is installed and then seeing if you can install chembl_structure_pipeline there?

**Comment by nbosc** [comment]
Hi @greglandrum,

OS: MacOS 10.15.7
Python tested: 3.7 and 3.8

Successful installation when using the conda-forge channel

**Comment by eloyfelix** [comment]
Hi Greg,

Since conda-forge guys are also making builds of the package I suggested him to install the package + rdkit using the conda-forge channel (not chembl nor rdkit channels) until we have time to investigate if his issue is due to the conda mac os version, channels conflict, etc...

I was also considering to recommend the users to install it using conda-forge. What do you think about it?

**Comment by greglandrum** [comment]
Yeah, I think pointing people to conda-forge totally makes sense.
We should update the docs... 
PR on its way.

**Comment by eloyfelix** [comment]
not sure why we didn't close this issue before but now can be also installed using pip
```
pip install chembl_structure_pipeline
```
