### ISSUE TITLE
Standardisation will change ECFP largely

### ISSUE THREAD

**Issue by zealseeker** [chembl/ChEMBL_Structure_Pipeline#23]
If we calculate ECFP instantly after the molecule is standardised, the ECFP will change largely compared to the original molecule, even though their exported SMILES are the same. It is because some "identical" substructures/features will merge in different bits.

I speculate that the atom feature is changed slightly, leading to the different symbolisation and finally their fingerprints become different.  Theoretically if we process the molecule consistently, the effect is ignorable. But some unconscious manipulations will be detrimental.

Personally I would prefer to export to SMILES after standardisation first. Then use the canonical smiles to do following procedures. But if someone changes the workflow, calculating ECFP instantly, the results will be quite different. 

Interestingly, RDK fingerprint is not affected.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/4076178/109866471-34870a00-7c5d-11eb-9f04-5ecc3035672c.png">

**Comment by greglandrum** [comment]
Hi @zealseeker,
You need to sanitize the molecule after it comes back from the standardizer. 

Here's a little demo:
```
In [5]: m = Chem.MolFromSmiles('CCOc1ccccc1-n1c(SCC(=O)Nc2ccc(CC)cc2)nc2nnc(C)c2c1N')

In [6]: m1 = standardizer.standardize_mol(m)
[04:59:30] Running Normalizer
[04:59:30] Running Uncharger

In [9]: fp = rdMolDescriptors.GetMorganFingerprintAsBitVect(m,2)

In [10]: fp1 = rdMolDescriptors.GetMorganFingerprintAsBitVect(m1,2)

In [11]: fp==fp1
Out[11]: False

In [12]: Chem.SanitizeMol(m1)
Out[12]: rdkit.Chem.rdmolops.SanitizeFlags.SANITIZE_NONE

In [13]: fp1 = rdMolDescriptors.GetMorganFingerprintAsBitVect(m1,2)

In [14]: fp==fp1
Out[14]: True
```
