### ISSUE TITLE
Chirality remove issue

### ISSUE THREAD

**Issue by peiyaoli** [chembl/ChEMBL_Structure_Pipeline#24]
Hi, first of all, thanks for open this pipeline which is really helpful for our molecule standardization work.

We came up one question regarding chiralty remove.

Input SMILES: `O=C(O)[C@@H]1O[B-]2(O[C@H]1C(=O)O)O[C@@H](C(=O)O)[C@H](C(=O)O)O2`

![download (3)](https://user-images.githubusercontent.com/18466185/124696791-4c76df00-df18-11eb-8392-c9cce62c39e5.png)

after "standardize_mol" and "get_parent_mol", the output molecule is:

OUT SMILES: `O=C(O)C1O[B-]2(O[C@H]1C(=O)O)O[C@@H](C(=O)O)[C@H](C(=O)O)O2`

It looks like only one chiralty has been removed.
![download (4)](https://user-images.githubusercontent.com/18466185/124696854-631d3600-df18-11eb-9312-576519bd402b.png)

@greglandrum How to resolve this issue? Many thanks...

**Comment by greglandrum** [comment]
I can reproduce this with `standardize_mol()`:
```
In [8]: res = standardizer.standardize_mol(Chem.MolFromSmiles('O=C(O)[C@@H]1O[B-]2(O[C@H]1C(=O)O)O[C@@H](C(=O)O)[C@H](C(=O)O)O2'
   ...: ))
[11:21:57] Running Normalizer
[11:21:57] Running Uncharger

In [9]: Chem.MolToSmiles(res)
Out[9]: 'O=C(O)C1O[B-]2(O[C@H]1C(=O)O)O[C@@H](C(=O)O)[C@H](C(=O)O)O2'
```
but not with `get_parent_mol()`:
```
In [5]: res,_ = standardizer.get_parent_mol(Chem.MolFromSmiles('O=C(O)[C@@H]1O[B-]2(O[C@H]1C(=O)O)O[C@@H](C(=O)O)[C@H](C(=O)O)O2
   ...: '))
[11:20:57] Running Uncharger
[11:20:57] Running Uncharger

In [6]: Chem.MolToSmiles(res)
Out[6]: 'O=C(O)[C@@H]1O[B-]2(O[C@H]1C(=O)O)O[C@@H](C(=O)O)[C@H](C(=O)O)O2'
```

I will look into it.

**Comment by greglandrum** [comment]
Ok, found it. The problem here is with `flatten_tartrate_mol()`
Fix on its way

**Comment by greglandrum** [comment]
The problem here is caused by errors in the `flatten_tartrate()` function, which has multiple problems.

**Comment by greglandrum** [comment]
Thanks for reporting this @peiyaoli !

**Comment by peiyaoli** [comment]
Welcome~

**Comment by eloyfelix** [comment]
Many thanks @peiyaoli for reporting and @greglandrum for the PR! :)

We are planing release a new version of the package for ChEMBL30.

Related to the new version... @greglandrum: will the new RDKit version builds ship with InChI 1.06?

**Comment by greglandrum** [comment]
> 
> Related to the new version... @greglandrum: will the new RDKit version builds ship with InChI 1.06?

That's definitely something we should do for the 2021.09 release.
Here's the issue: https://github.com/rdkit/rdkit/issues/4322

**Comment by eloyfelix** [comment]
that's great, many thanks again
