### ISSUE TITLE
deuterium (2H) gets converted to 1H

### ISSUE THREAD

**Issue by GLPG-GT** [chembl/ChEMBL_Structure_Pipeline#35]
```
from rdkit import Chem
from chembl_structure_pipeline import standardizer
mb = """
  ACCLDraw12152117212D

  0  0  0     0  0            999 V3000
M  V30 BEGIN CTAB
M  V30 COUNTS 9 9 0 0 0
M  V30 BEGIN ATOM
M  V30 1 C 2.634 -5.2839 0 0 
M  V30 2 C 3.6571 -4.6936 0 0 
M  V30 3 C 4.6763 -5.2833 0 0 
M  V30 4 C 4.6763 -6.4648 0 0 
M  V30 5 C 3.6597 -7.0543 0 0 
M  V30 6 C 2.634 -6.4701 0 0 
M  V30 7 D 3.6571 -3.5121 0 0 
M  V30 8 D 5.6995 -4.6926 0 0 
M  V30 9 D 5.6995 -7.0555 0 0 
M  V30 END ATOM
M  V30 BEGIN BOND
M  V30 1 2 2 1 
M  V30 2 1 3 2 
M  V30 3 2 4 3 
M  V30 4 1 5 4 
M  V30 5 1 1 6 
M  V30 6 2 6 5 
M  V30 7 1 2 7 
M  V30 8 1 3 8 
M  V30 9 1 4 9 
M  V30 END BOND
M  V30 END CTAB
M  END
"""
m = Chem.MolFromMolBlock(mb)
m
```
![benzene_with_3_deuterium_atoms_pre_std](https://user-images.githubusercontent.com/96192927/146225744-6066fb80-c0ab-4cf4-89b2-0bd9b78fbd47.png)

```
mb = Chem.rdmolfiles.MolToMolBlock(m)
mb = standardizer.standardize_molblock(mb)
mb, _ = standardizer.get_parent_molblock(mb)
m_new = Chem.rdmolfiles.MolFromMolBlock(mb)
m_new
```
![benzene_with_3_deuterium_atoms_post_std](https://user-images.githubusercontent.com/96192927/146225949-f2aaf254-625b-4ec4-a59c-a70c1924605c.png)

Is there any option one can use to stop this from happening?
(also, not clear why it is done by default; it's a data-integrity-altering action, so it should be done only on explicit request, shouldn't it?)

**Comment by greglandrum** [comment]
@GLPG-GT : this is by design
The standardizer itself does not remove isotopes:
```
In [28]: print(mb)

     RDKit          2D

  3  2  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2990    0.7500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.5981   -0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
M  ISO  1   3   2
M  END

In [31]: print(standardizer.standardize_molblock(mb))
[12:35:59] Running Normalizer
[12:35:59] Running Uncharger

     RDKit          2D

  3  2  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2990    0.7500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.5981   -0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
M  ISO  1   3   2
M  END

```
but `get_parent_molblock()` does:
```
In [34]: print(standardizer.get_parent_molblock(mb)[0])
[12:36:30] Running Uncharger

     RDKit          2D

  2  1  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2990    0.7500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
M  END
```
This is documented here: https://github.com/chembl/ChEMBL_Structure_Pipeline/wiki/Work-done-by-each-step#get_parent_molblock

Note that `get_parent_molblock()` removes all isotope information:
```
In [37]: print(mb)

     RDKit          2D

  3  2  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2990    0.7500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.5981   -0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
M  ISO  2   1  13   3   2
M  END


In [38]: print(standardizer.standardize_molblock(mb))
[12:39:59] Running Normalizer
[12:39:59] Running Uncharger

     RDKit          2D

  3  2  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2990    0.7500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.5981   -0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
M  ISO  2   1  13   3   2
M  END


In [39]: print(standardizer.get_parent_molblock(mb)[0])
[12:40:03] Running Uncharger

     RDKit          2D

  2  1  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2990    0.7500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
M  END

```

**Comment by GLPG-GT** [comment]
@greglandrum 
Thank you for the explanation.
We will not be able to use the get_parent_molblock() functionality then, as for us (drug discovery) a molecule with D replaced by H is a completely different chemical entity.
We will probably use rdkit.Chem.MolStandardize.rdMolStandardize.LargestFragmentChooser , which we tested and does not seem to do this.

**Comment by greglandrum** [comment]
> @greglandrum Thank you for the explanation. We will not be able to use the get_parent_molblock() functionality then, as for us (drug discovery) a molecule with D replaced by H is a completely different chemical entity. We will probably use rdkit.Chem.MolStandardize.rdMolStandardize.LargestFragmentChooser , which we tested and does not seem to do this.

@GLPG-GT : The parent molblock functionality here is designed for a different use case than what you want, so I think that it could make perfect sense to use the standardization code here (assuming that you're happy with the ChEMBL standardization rules) and then the RDKit's default largest fragment chooser to remove salts and solvents
