### ISSUE TITLE
Status output being written to stdout instead of stderr

### ISSUE THREAD

**Issue by gpatbrady** [chembl/ChEMBL_Structure_Pipeline#36]
Thank you for this pipeline; very helpful!
I am writing a python command line wrapper to some of this functionality and it appears to me that some of the "runtime" info that ought to be sent to stderr is being sent to stdout.  I'm using the standardize() and get_parent_mol() functions in particular, and my output (to stdout) is being polluted with e.g. stuff like

[21:22:44] Initializing Normalizer
[21:22:44] Running Uncharger
[21:22:44] Running Uncharger
[21:22:44] Running Normalizer
[21:22:44] Running Uncharger
[21:22:44] Running Uncharger
[21:22:44] Running Uncharger

Cheers,
pat

**Comment by gpatbrady** [comment]
Or a way to suppress this output altogether would be great.

**Comment by greglandrum** [comment]
@gpatbrady, those messages are coming from the RDKit core.
The incantation to disable the RDKit info log is:
```
from rdkit import RDLogger
RDLogger.DisableLog("rdApp.info")
```

**Comment by gpatbrady** [comment]
Oh sweet; I'll give that a shot!
Thanks!
Pat
