### ISSUE TITLE
Non-canonical SMILES after standardization

### ISSUE THREAD

**Issue by rflameiro** [chembl/ChEMBL_Structure_Pipeline#37]
Hi, I have been using the following function for standardizing structures, and since it involves converting SMILES to RDKit_mol, and back to SMILES, I assumed that the output SMILES would be the RDKit canonical, but this does not seem to be the case. As an example:

```
from chembl_structure_pipeline import standardizer
from rdkit import Chem

# Function used to standardize
def standardize_smiles(smiles):
    try:
        # Convert to RDKit mol
        m = Chem.MolFromSmiles(smiles)
        # Neutralize and separate from counterion
        m = standardizer.get_parent_mol(m, neutralize=True, check_exclusion=True, verbose=False)[0]
        # Standardize representation
        m = standardizer.standardize_mol(m, check_exclusion=True)
        # Return RDKit canonical SMILES
        return Chem.MolToSmiles(m, isomericSmiles=False)
    except:
        return np.nan

# Example SMILES that represent the same structure, but do not yield the same string after standardization
smi1 = 'CCC(C(C)O)n1ncn(-c2ccc(N3CCN(c4ccc(OCC5COC(Cn6cncn6)(c6c(F)cc(F)cc6)C5)cc4)CC3)cc2)c1=O'
smi2 = 'CCC(C(C)O)n1ncn(-c2ccc(N3CCN(c4ccc(OCC5COC(Cn6cncn6)(c6ccc(F)cc6F)C5)cc4)CC3)cc2)c1=O'

# Using standardize_smiles()
standardize_smiles(smi1) == standardize_smiles(smi2)
>>> False

# Sanity check with RDKit
Chem.MolToSmiles(Chem.MolFromSmiles(smi1)) == Chem.MolToSmiles(Chem.MolFromSmiles(smi2))
>>> True
```

This persists even if I remove the isomericSmiles argument from the final step. 
Is this the expected behavior or am I not using the module properly?
Thanks in advance.

**Comment by rflameiro** [comment]
I also noticed that this function will not standardize tautomeric forms. I guess it just doesn't do what I thought it would. 

The function shown [here](https://bitsilla.com/blog/2021/06/standardizing-a-molecule-using-rdkit/) seems to do the trick. Just include `Chem.MolToSmiles(m, isomericSmiles=False)` if that is what you need.

**Comment by greglandrum** [comment]
> I also noticed that this function will not standardize tautomeric forms. I guess it just doesn't do what I thought it would.
> 

Correct. This code does not do tautomer enumeration. The [wiki](https://github.com/chembl/ChEMBL_Structure_Pipeline/wiki) is pretty explicit about what the operations performed are.

**Comment by eloyfelix** [comment]
`standardizer.standardize_mol` in master sanitizes the molecules by default now. SMILES are now canonical.
