### ISSUE TITLE
testBondDoubleStereoProblem1 test fails in Python 3.9.8 and rdkit versions >=2021.9.1b1

### ISSUE THREAD

**Issue by djm-healx** [chembl/ChEMBL_Structure_Pipeline#39]
The assertion in the following statement fails when running `unittest` in Python 3.9.8, using `rdkit` version 2022.3.1:
https://github.com/chembl/ChEMBL_Structure_Pipeline/blob/8d599ad389a458c002be9fd8353a91ebaf370743/chembl_structure_pipeline/test/test_standardizer.py#L1655

Which raises:
```
FAIL: testDoubleBondStereoProblem1 (test.test_standardizer.TestCase)
a problem found in testing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/danielmason/Healx/repositories/ChEMBL_Structure_Pipeline/chembl_structure_pipeline/test/test_standardizer.py", line 1655, in testDoubleBondStereoProblem1
    self.assertNotEqual(omolb.find('13 12  1  6'), -1)
AssertionError: -1 == -1
```

This was picked up in #38 when running `python -m unittest discover chembl_structure_pipeline` to test after creating the PR.

Is this expected behaviour, or an unexpected failure?

**Comment by djm-healx** [comment]
The tests pass using rdkit 2021.3.1.5

**Comment by eloyfelix** [comment]
thanks for reporting! I've just confirmed the bug and we'll need to take a look at it.

**Comment by eloyfelix** [comment]
sorry for the long silence. We had lots of work related to data lately. RDKit 2022.09.01 passes again the tests. We'll release a new version of the standardiser soon (will be included in pypi) and it will be used in ChEMBL after we release the next version, ChEMBL32
