### ISSUE TITLE
get_parent_mol "doesn't work" for all salts

### ISSUE THREAD

**Issue by rflameiro** [chembl/ChEMBL_Structure_Pipeline#51]
For instance, applying `get_parent_mol` to sodium benzoate does not return benzoic acid, but sodium benzoate. This happens because both sodium and benzoate are on the salts.smi list, and `get_fragment_parent_mol` returns the entire input when all fragments are excluded.

Since this might not be the expected behaviour for all users of ChEMBL_Structure_Pipeline, I believe this piece of code ([source](https://www.insilico.jp/blog/2021/11/16/chembl-structure-pipeline/)) will provide a solution.

```
from rdkit import Chem
from rdkit.Chem.MolStandardize import rdMolStandardize
from chembl_structure_pipeline import standardizer

def new_standardize_mol(molecule, return_mol=True):
    """
    molecule: RDKitMol object
    return_mol: Indicates if output will be an RDKit Mol object (True) or a SMILES string (False)
    """
    try:
        # Apply standardize_mol
        std1_mol = standardizer.standardize_mol(molecule)
        # Select largest fragment
        desalter = rdMolStandardize.LargestFragmentChooser()
        desalt_mol = desalter.choose(std1_mol)
        # Apply standardize_mol to the largest fragment
        curated_mol = standardizer.standardize_mol(desalt_mol)
        
        if return_mol:
            return curated_mol
        else:
            return Chem.MolToSmiles(curated_mol)
    
    except Exception as e: 
        print(e)
        print("Error, skipping current compound.")
        return
```

**Comment by eloyfelix** [comment]
Sorry for the slow reply. This is the expected behaviour of the get_parent_mol function, please see:

https://github.com/chembl/ChEMBL_Structure_Pipeline/wiki/Work-done-by-each-step#get_parent_molblock
