### ISSUE TITLE
ChEMBL InChIKey/InChI computation

### ISSUE THREAD

**Issue by phytophreak** [chembl/ChEMBL_Structure_Pipeline#53]
Hi,

I'm trying to merge an external dataset with the compounds in the ChEMBL database. My approach is to use the `standard_inchi_key` as unique identifier. To ensure that the external dataset is processed in the same way, the external compounds are first standardized using the `chembl_structure_pipeline` (`standardizer.standardize_mol()`).

In my first try, I used RDKit to compute the InChIKey from the standardized structures. But I quickly realized that this leads to some inconsistencies with the ChEMBL data. The "An open source chemical structure curation pipeline using RDKit" publication gave some clarification on that and now I'm also using the InChI Trust software to compute InChIKeys. This solved some problems, but it seems like it also opened others, as I'm not able to reproduce some of the InChIKeys in ChEMBL.

The following example shows that for two compounds, the InChIKeys produced by both RDKit and `inchi` (using `./inchi-1 -Key <molfile>`) are different to the `standard_inchi_key` in ChEMBL:

```python
from rdkit import Chem

# https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2391680/
# standard_inchi_key: RNSAWGNXDCNAAY-DXDUWVORSA-N
s1 = "Fc1ccc2c(c1)c1cc[n+]2Cc2cccc(c2)C[n+]2ccc(c3cc(F)ccc32)NCc2ccc(cc2)CN1.O=C([O-])C(F)(F)F.O=C([O-])C(F)(F)F"
# https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL3629243/
# standard_inchi_key: MFUROMODHKJRGA-FTQBRHHNSA-N
s2 = "COc1cc(O)c2c(c1)/C=C/C[C@@H]1OC(C)(C)O[C@@H]1C(=O)/C=C\C[C@H](C)OC2=O"


def to_inchi_key(s):
    m = Chem.MolFromSmiles(s)
    return Chem.MolToInchiKey(m)


def to_mol_file(s, file):
    m = Chem.MolFromSmiles(s)
    return Chem.MolToMolFile(m, filename=file)


# RDKit produces different InChIKeys:
print(to_inchi_key(s1))
# > RNSAWGNXDCNAAY-UHFFFAOYSA-N
print(to_inchi_key(s2))
# > MFUROMODHKJRGA-VMSLBYTRSA-N

# The inchi software also produces different InChIKeys:
to_mol_file(s1, "m1.mol")
# inchi output for m1.mol:
# InChI=1S/C34H26F2N4.2C2HF3O2/c35-27-8-10-33-29(17-27)31-12-14-39(33)21-25-2-1-3-26(16-25)22-40-15-13-32(30-18-28(36)9-11-34(30)40)38-20-24-6-4-23(5-7-24)19-37-31;2*3-2(4,5)1(6)7/h1-18H,19-22H2;2*(H,6,7)/b37-31-,38-32+;;
# InChIKey=RNSAWGNXDCNAAY-JGIQTYTPSA-N

to_mol_file(s2, "m2.mol")
# inchi output for m2.mol:
# InChI=1S/C22H26O7/c1-13-7-5-9-16(23)20-18(28-22(2,3)29-20)10-6-8-14-11-15(26-4)12-17(24)19(14)21(25)27-13/h5-6,8-9,11-13,18,20,24H,7,10H2,1-4H3/b8-6-,9-5-/t13-,18-,20+/m0/s1
# InChIKey=MFUROMODHKJRGA-ZAYVECMYSA-N
```

Software versions:

* `rdkit` version 2023.3.3
* `chembl_structure_pipeline` version 1.2.0
* [InChI](https://www.inchi-trust.org/downloads/) version 1.0.6

My question now is if there is a reproducible way to generate InChIKeys from ChEMBL compounds? Maybe I'm missing something or my approach has other flaws. I would be really glad if someone can help me.

Or maybe you have a better idea on how an external dataset can be merged.

Thank you,
Bernhard

**Comment by eloyfelix** [comment]
Hi Bernhard,

Our deposited structures come from molfiles. We do calculate SMILES for each structure using default RDKit parameters but we trust molfiles as the primary representation of the molecules.

<img width="849" alt="Screenshot 2023-10-04 at 09 46 56" src="https://github.com/chembl/ChEMBL_Structure_Pipeline/assets/1122541/9b996eb1-ba75-4524-beaf-d11fdd6cbaf8">

We do use the `MolBlockToInchi` RDKit function that bypasses any RDKit related sanitization of the molecules which could potentially bring changes to the molecules.

If you use our provided molfiles with the inchi binary you should get the same InChI the code below is calculating (which is the way we do it at ChEMBL).


```python
from rdkit import Chem

# https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2391680/
# standard_inchi_key: RNSAWGNXDCNAAY-DXDUWVORSA-N
mol1 = """
     RDKit          2D

 54 58  0  0  0  0  0  0  0  0999 V2000
    7.4469  -11.7171    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.6297  -11.7135    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.8523  -12.4281    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    7.8586  -11.0099    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    6.2179  -12.4193    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
    6.2243  -11.0039    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
    5.8121  -11.7105    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
    2.7332   -7.6138    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.5564   -7.6149    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.9672   -6.9037    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.5560   -6.1909    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.7296   -6.1938    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.3225   -6.9055    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.4656   -8.1682    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.4645   -8.9955    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.1792   -9.4084    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    5.1775   -7.7554    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.8929   -8.1645    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.8936   -8.9913    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.6089   -9.4022    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.3239   -8.9875    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    7.3191   -8.1576    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.6033   -7.7503    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.1821   -6.9324    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.8893   -9.3654    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    1.6058   -8.9520    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.6028   -8.1215    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8875   -7.7124    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.1744   -8.9525    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.1768   -8.1269    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5391   -7.7140    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2570   -8.1254    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2503   -8.9541    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5386   -9.3634    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8956   -6.8904    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    1.6140   -6.4849    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.4716   -6.5129    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.1811  -10.2334    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.8427  -10.7891    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.4138  -10.7883    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8900  -10.1900    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.4140  -11.6188    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.1289  -12.0317    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.8452  -11.6183    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.1270  -10.3786    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9674   -7.7131    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
    8.0311   -7.7407    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5995  -12.4863    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4167  -12.4826    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1941  -13.1972    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1878  -11.7790    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8285  -13.1885    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8221  -11.7731    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2343  -12.4796    0.0000 F   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  1  3  2  0
  1  4  1  0
  2  5  1  0
  2  6  1  0
  2  7  1  0
  8  9  2  0
  9 10  1  0
 10 11  2  0
 11 12  1  0
 12 13  2  0
 13  8  1  0
 14 15  2  0
 15 16  1  0
 16 19  2  0
 18 17  2  0
 17 14  1  0
 18 19  1  0
 19 20  1  0
 20 21  2  0
 21 22  1  0
 22 23  2  0
 23 18  1  0
 24 17  1  0
 29 25  1  0
 25 26  2  0
 26 27  1  0
 27 28  2  0
 28 30  1  0
 29 30  1  0
 30 31  2  0
 31 32  1  0
 32 33  2  0
 33 34  1  0
 34 29  2  0
 35 28  1  0
 35 36  1  0
 36 13  1  0
 37 24  1  0
 25 41  1  0
 16 38  1  0
 38 39  1  0
 40 41  1  0
 37 10  1  0
 40 42  2  0
 42 43  1  0
 43 44  2  0
 44 39  1  0
 39 45  2  0
 45 40  1  0
 32 46  1  0
 22 47  1  0
 48 49  1  0
 48 50  2  0
 48 51  1  0
 49 52  1  0
 49 53  1  0
 49 54  1  0
M  CHG  4   4  -1  16   1  25   1  51  -1
M  END
> <chembl_id>
CHEMBL2391680

> <chembl_pref_name>
None
"""



print(Chem.InchiToInchiKey(Chem.MolBlockToInchi(mol1)))


# https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL3629243/
# standard_inchi_key: MFUROMODHKJRGA-FTQBRHHNSA-N
mol2 = """
     RDKit          2D

 31 33  0  0  0  0  0  0  0  0999 V2000
    3.8868    4.8556    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.4987    5.4240    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3124    4.5060    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.0887    3.3692    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.9090    2.4485    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5082    3.0221    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2751    2.1127    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.0940    0.9797    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8376   -1.3296    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8850    0.1457    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.4303   -1.7651    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4112   -2.0819    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5452   -3.3168    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0770   -3.1453    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7776   -0.6908    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0904    2.7615    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4028    1.9759    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.7181    0.4840    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.1892    0.4894    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -4.0207   -0.0276    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4472   -1.8755    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.6061   -2.1923    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.7919   -2.0572    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.2001    2.9168    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.2937    6.9107    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.1825    7.3638    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.9052   -1.5232    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.0297   -1.1040    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.6708   -2.7000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.4814    1.1301    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7790   -0.6381    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  6  2  0
  5  4  2  0
  4  1  1  0
  5  6  1  0
  5  8  1  0
  6  7  1  0
  7 16  2  0
  8 10  1  0
 11  9  1  0
  9 10  1  0
 11 14  1  0
 15 12  1  0
 12 13  1  0
 13 14  2  0
 15 18  1  0
 16 17  1  0
 17 18  1  0
  8 19  2  0
 18 20  1  0
 15 21  1  0
 12 22  2  0
  9 23  1  1
  4 24  1  0
 25 26  1  0
  2 25  1  0
 20 27  1  0
 21 27  1  0
 27 28  1  0
 27 29  1  0
 18 30  1  6
 15 31  1  6
M  END
> <chembl_id>
CHEMBL3629243

> <chembl_pref_name>
None
"""

print(Chem.InchiToInchiKey(Chem.MolBlockToInchi(mol2)))

```

Software versions used for ChEMBL_33: 

[rdkit](https://pypi.python.org/pypi/rdkit)==2022.09.4
[chembl_structure_pipeline](https://pypi.python.org/pypi/chembl_structure_pipeline)==1.2.0

**Comment by phytophreak** [comment]
Hi Eloy, 

thank you for your quick reply! This already explains a lot.

But it leaves another question to me: Is there a way to generate those exact molblocks from the canonical SMILES in ChEMBL? I guess when the ChEMBL database is populated with new compounds, those molblocks first need to be generated from the standardized structures computed by the `chembl_structure_pipeline`? I have tried a few options to load the SMILES using RDKit and then export the mol object as molblock, but the resulting molblocks never matched the ones in the database 🙈  

For ChEMBL I could of course use molblocks instead of SMILES. But when processing other datasets, I usually only have SMILES and need a way to generate the molblocks/InChIs/InChIKeys in the same way.

Thank you,
Bernhard

**Comment by phytophreak** [comment]
> Hi Eloy,
> 
> thank you for your quick reply! This already explains a lot.
> 
> But it leaves another question to me: Is there a way to generate those exact molblocks from the canonical SMILES in ChEMBL? I guess when the ChEMBL database is populated with new compounds, those molblocks first need to be generated from the standardized structures computed by the `chembl_structure_pipeline`? I have tried a few options to load the SMILES using RDKit and then export the mol object as molblock, but the resulting molblocks never matched the ones in the database 🙈
> 
> For ChEMBL I could of course use molblocks instead of SMILES. But when processing other datasets, I usually only have SMILES and need a way to generate the molblocks/InChIs/InChIKeys in the same way.
> 
> Thank you, Bernhard

Hi @eloyfelix, 

I don't know if you get a notification on already closed issues, so I will just try it this way 🙈😄 I would be really glad if you can help me on this, as I am running out of ideas.

Thank you,
Bernhard

**Comment by greglandrum** [comment]
> 
> But it leaves another question to me: Is there a way to generate those exact molblocks from the canonical SMILES in ChEMBL? I guess when the ChEMBL database is populated with new compounds, those molblocks first need to be generated from the standardized structures computed by the `chembl_structure_pipeline`? I have tried a few options to load the SMILES using RDKit and then export the mol object as molblock, but the resulting molblocks never matched the ones in the database 🙈

You cannot generate the exact mol blocks found in ChEMBL from the SMILES found in ChEMBL. Mol blocks contain information like atomic coordinates and bond wedging which is not present in SMILES. That information is lost when doing the Mol block -> SMILES conversion.

> For ChEMBL I could of course use molblocks instead of SMILES. But when processing other datasets, I usually only have SMILES and need a way to generate the molblocks/InChIs/InChIKeys in the same way.

What exactly do you want to do? If you want to convert SMILES -> InChI you need to convert the SMILES into an RDKit molecule and then call MolToInchi on that:
```
In [2]: m = Chem.MolFromSmiles("C1CC2CCOC3OC4CCC(C1)C23OO4")

In [3]: Chem.MolToInchi(m)
[06:46:48] WARNING: Omitted undefined stereo

Out[3]: 'InChI=1S/C12H18O4/c1-2-8-4-5-10-14-11-12(8,16-15-10)9(3-1)6-7-13-11/h8-11H,1-7H2'
```
If you want to convert a mol block to InChI you have two options:
1. call `Chem.MolBlockToInchi()`: this skips the RDKit's chemistry perception and cleanup
2. convert the mol block into an RDKit molecule and call `Chem.MolToInchi()` on that. This uses the RDKit's chemistry perception and cleanup

**Comment by phytophreak** [comment]
> You cannot generate the exact mol blocks found in ChEMBL from the SMILES found in ChEMBL. Mol blocks contain information like atomic coordinates and bond wedging which is not present in SMILES. That information is lost when doing the Mol block -> SMILES conversion.

Ok thank you, I was already expecting that.
 
> > For ChEMBL I could of course use molblocks instead of SMILES. But when processing other datasets, I usually only have SMILES and need a way to generate the molblocks/InChIs/InChIKeys in the same way.
> 
> What exactly do you want to do? If you want to convert SMILES -> InChI you need to convert the SMILES into an RDKit molecule and then call MolToInchi on that:

Ok I think I now understood that my approach will never be perfect 😄 Let's say that for a new dataset we only know the SMILES. So the first step will be to generate InChIKeys from those SMILES in the new dataset and try to match them with the InChIKeys in the ChEMBL database. But now it can happen that a compound is already present in ChEMBL, while the InChIKey produced by the SMILES -> InChIKey conversion is different from the one in ChEMBL. Or two compounds are matched but they are actually only stereoisomers of each other. 

But anyway, this will probably not happen too often. I guess I just have to live with a few duplicates or mismatches. And in addition to the InChIKey matching, I could probably also check if the standardized SMILES are equal. 

Thank you for your help!

**Comment by greglandrum** [comment]
> Ok I think I now understood that my approach will never be perfect 😄 Let's say that for a new dataset we only know the SMILES. So the first step will be to generate InChIKeys from those SMILES in the new dataset and try to match them with the InChIKeys in the ChEMBL database. But now it can happen that a compound is already present in ChEMBL, while the InChIKey produced by the SMILES -> InChIKey conversion is different from the one in ChEMBL. Or two compounds are matched but they are actually only stereoisomers of each other.

There should only be a small number of cases where this happens. These are cases where the RDKit interprets the stereochemistyr in the mol block differently than the InChI code does.
